#+TITLE: Starter Kit LaTeX
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit LaTeX
  Support for editing LaTeX.

** Load Packages
*** Load AucTeX
#+begin_src emacs-lisp
  (load "auctex.el" nil t t)
#+end_src

*** Load Preview LaTeX
#+begin_src emacs-lisp
  (load "preview-latex.el" nil t t)
#+end_src

*** Load RefTeX
#+srcname: reftex-support
#+begin_src emacs-lisp 
  (add-hook 'LaTeX-mode-hook 'turn-on-reftex)   ; with AUCTeX LaTeX mode
  (autoload 'reftex-mode     "reftex" "RefTeX Minor Mode" t)
  (autoload 'turn-on-reftex  "reftex" "RefTeX Minor Mode" nil)
  (autoload 'reftex-citation "reftex-cite" "Make citation" nil)
  (autoload 'reftex-index-phrase-mode "reftex-index" "Phrase mode" t)
  (add-hook 'LaTeX-mode-hook 'turn-on-reftex)   ; with AUCTeX LaTeX mode
  (add-hook 'latex-mode-hook 'turn-on-reftex)   ; with Emacs latex mode
  
  ;; Make RefTeX faster
  (setq reftex-enable-partial-scans t)
  (setq reftex-save-parse-info t)
  (setq reftex-use-multiple-selection-buffers t)
  (setq reftex-plug-into-AUCTeX t)
  
  ;; Make RefTeX work with Org-Mode
  ;; use 'C-c (' instead of 'C-c [' because the latter is already
  ;; defined in orgmode to the add-to-agenda command.
  (defun org-mode-reftex-setup ()
    (load-library "reftex") 
    (and (buffer-file-name)
    (file-exists-p (buffer-file-name))
    (reftex-parse-all))
    (define-key org-mode-map (kbd "C-c (") 'reftex-citation))
  
  (add-hook 'org-mode-hook 'org-mode-reftex-setup)
  
  ;; RefTeX formats for biblatex (not natbib)
  (setq reftex-cite-format
        '(
          (?\C-m . "\\cite[]{%l}")
          (?t . "\\textcite{%l}")
          (?a . "\\autocite[]{%l}")
          (?p . "\\parencite{%l}")
          (?f . "\\footcite[][]{%l}")
          (?F . "\\fullcite[]{%l}")
          (?x . "[]{%l}")
          (?X . "{%l}")
          ))
  
  (setq font-latex-match-reference-keywords
        '(("cite" "[{")
          ("cites" "[{}]")
          ("footcite" "[{")
          ("footcites" "[{")
          ("parencite" "[{")
          ("textcite" "[{")
          ("fullcite" "[{") 
          ("citetitle" "[{") 
          ("citetitles" "[{") 
          ("headlessfullcite" "[{")))
  
  (setq reftex-cite-prompt-optional-args nil)
  (setq reftex-cite-cleanup-optional-args t)
  
#+end_src

** Configure AucTeX 
*** Use pdfLaTeX
    - Take this out to compile to DVI, instead.
#+srcname: pdf-mode
#+begin_src emacs-lisp 
      (add-hook 'LaTeX-mode-hook 'TeX-PDF-mode)
#+end_src

*** Set a Path to Executables (optional)
    - The location of the LaTeX excecutables is system
      dependent. AUCTeX calls everything through a shell, so you may
      or may not need this.  This source-code block is turned off by
      default as it should be added to the user's personal
      configuration as needed.
#+srcname: set-exec-path
#+begin_src emacs-lisp :tangle no
      (setenv "PATH" (concat "/usr/texbin:" (getenv "PATH")))
#+end_src

** Configure RefTeX
*** Default Bibliography
    - This is important when editing source code in Org-babel, since
      the LaTeX source code block being edited probably doesn't
      include the \bibliography{} command that RefTeX uses to find
      bibliographic database(s).  Make certain also that RefTeX has a
      path to the bibliographic databases.  This source-code block is
      turned off be default as it should be configured by the user in
      a personal file/directory.
#+srcname: default-bibliography
#+begin_src emacs-lisp :tangle no
  (setq reftex-default-bibliography
        (quote
         ("user.bib" "local.bib")))
#+end_src

** Configure Org-babel
   - Add LaTeX to the list of languages Org-babel will recognize.
#+srcname: add-latex
#+begin_src emacs-lisp 
     (require 'ob-latex)
  ;; (org-babel-add-interpreter "latex")
  ;; (add-to-list 'org-babel-tangle-langs '("latex" "tex"))
  ;; ; (require 'org-babel-latex)
#+end_src
   - Add LaTeX to a list of languages that raise noweb-type errors.
#+srcname: noweb-error
#+begin_src emacs-lisp 
  (add-to-list 'org-babel-noweb-error-langs "latex")
#+end_src

  
